In [2]:
import os

#importing libraries
import pandas as pd  # data processing, CSV file I/O (e.g. pd.read_csv)
import numpy as np # linear algebra
from matplotlib import pyplot as plt
import seaborn as sns

#automated feature generation tools
import featuretools as ft 
from tsfresh import extract_features
from tsfresh import extract_relevant_features

In [5]:
df = pd.read_csv('./Data/1_out.csv', parse_dates=['date'])
df = df.dropna()
df["store_item"] = df["store"].astype(str) +  "," + df["item"].astype(str)
y = df["sales"]

df = df.drop(columns=["Unnamed: 0"])
df = df[["date","month","day_of_month","week_of_year","day_of_year","day_of_week","year","store_item"]]
df

,date,month,day_of_month,week_of_year,day_of_year,day_of_week,year,store_item
0,2013-01-01,1,1,1,1,1,2013,"1,1"
1,2013-01-02,1,2,1,2,2,2013,"1,1"
2,2013-01-03,1,3,1,3,3,2013,"1,1"
3,2013-01-04,1,4,1,4,4,2013,"1,1"
4,2013-01-05,1,5,1,5,5,2013,"1,1"
...,...,...,...,...,...,...,...,...
912995,2017-12-27,12,27,52,361,2,2017,"10,50"
912996,2017-12-28,12,28,52,362,3,2017,"10,50"
912997,2017-12-29,12,29,52,363,4,2017,"10,50"
912998,2017-12-30,12,30,52,364,5,2017,"10,50"
912999,2017-12-31,12,31,52,365,6,2017,"10,50"

<h1>Automated Feature Generation 
<h2>tsFresh Feature Extraction

In [6]:
extracted_features = extract_features(df,column_id="store_item",column_sort="date")
extracted_features

Feature Extraction: 100%|██████████| 30/30 [28:45<00:00, 57.52s/it]

,day_of_week__variance_larger_than_standard_deviation,day_of_week__has_duplicate_max,day_of_week__has_duplicate_min,day_of_week__has_duplicate,day_of_week__sum_values,day_of_week__abs_energy,day_of_week__mean_abs_change,day_of_week__mean_change,day_of_week__mean_second_derivative_central,day_of_week__median,...,day_of_year__permutation_entropy__dimension_6__tau_1,day_of_year__permutation_entropy__dimension_7__tau_1,day_of_year__query_similarity_count__query_None__threshold_0.0,"day_of_year__matrix_profile__feature_""min""__threshold_0.98","day_of_year__matrix_profile__feature_""max""__threshold_0.98","day_of_year__matrix_profile__feature_""mean""__threshold_0.98","day_of_year__matrix_profile__feature_""median""__threshold_0.98","day_of_year__matrix_profile__feature_""25""__threshold_0.98","day_of_year__matrix_profile__feature_""75""__threshold_0.98",day_of_year__mean_n_absolute_max__number_of_maxima_7
"1,1",1.0,1.0,1.0,1.0,5481.0,23751.0,1.712329,0.00274,0.0,3.0,...,0.078148,0.093807,NaN,0.0,3.650137,2.835878,3.397513,3.355003,3.500442,365.0
"1,10",1.0,1.0,1.0,1.0,5481.0,23751.0,1.712329,0.00274,0.0,3.0,...,0.078148,0.093807,NaN,0.0,3.650137,2.835878,3.397513,3.355003,3.500442,365.0
"1,11",1.0,1.0,1.0,1.0,5481.0,23751.0,1.712329,0.00274,0.0,3.0,...,0.078148,0.093807,NaN,0.0,3.650137,2.835878,3.397513,3.355003,3.500442,365.0
"1,12",1.0,1.0,1.0,1.0,5481.0,23751.0,1.712329,0.00274,0.0,3.0,...,0.078148,0.093807,NaN,0.0,3.650137,2.835878,3.397513,3.355003,3.500442,365.0
"1,13",1.0,1.0,1.0,1.0,5481.0,23751.0,1.712329,0.00274,0.0,3.0,...,0.078148,0.093807,NaN,0.0,3.650137,2.835878,3.397513,3.355003,3.500442,365.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
"9,50",1.0,1.0,1.0,1.0,5481.0,23751.0,1.712329,0.00274,0.0,3.0,...,0.078148,0.093807,NaN,0.0,3.650137,2.835878,3.397513,3.355003,3.500442,365.0
"9,6",1.0,1.0,1.0,1.0,5481.0,23751.0,1.712329,0.00274,0.0,3.0,...,0.078148,0.093807,NaN,0.0,3.650137,2.835878,3.397513,3.355003,3.500442,365.0
"9,7",1.0,1.0,1.0,1.0,5481.0,23751.0,1.712329,0.00274,0.0,3.0,...,0.078148,0.093807,NaN,0.0,3.650137,2.835878,3.397513,3.355003,3.500442,365.0
"9,8",1.0,1.0,1.0,1.0,5481.0,23751.0,1.712329,0.00274,0.0,3.0,...,0.078148,0.093807,NaN,0.0,3.650137,2.835878,3.397513,3.355003,3.500442,365.0
"9,9",1.0,1.0,1.0,1.0,5481.0,23751.0,1.712329,0.00274,0.0,3.0,...,0.078148,0.093807,NaN,0.0,3.650137,2.835878,3.397513,3.355003,3.500442,365.0

In [7]:
from tsfresh.utilities.dataframe_functions import impute
impute(extracted_features)
from tsfresh import select_features
filtered_features = select_features(extracted_features, y)
filtered_features

/Users/skylivingston/.local/share/virtualenvs/CZ4041_Kaggle-e-ZUlYZi/lib/python3.9/site-packages/tsfresh/utilities/dataframe_functions.py:198: RuntimeWarning: The columns ['day_of_week__friedrich_coefficients__coeff_0__m_3__r_30'
 'day_of_week__friedrich_coefficients__coeff_1__m_3__r_30'
 'day_of_week__friedrich_coefficients__coeff_2__m_3__r_30'
 'day_of_week__friedrich_coefficients__coeff_3__m_3__r_30'
 'day_of_week__max_langevin_fixed_point__m_3__r_30'
 'day_of_week__query_similarity_count__query_None__threshold_0.0'
 'year__friedrich_coefficients__coeff_0__m_3__r_30'
 'year__friedrich_coefficients__coeff_1__m_3__r_30'
 'year__friedrich_coefficients__coeff_2__m_3__r_30'
 'year__friedrich_coefficients__coeff_3__m_3__r_30'
 'year__max_langevin_fixed_point__m_3__r_30'
 'year__query_similarity_count__query_None__threshold_0.0'
 'month__friedrich_coefficients__coeff_0__m_3__r_30'
 'month__friedrich_coefficients__coeff_1__m_3__r_30'
 'month__friedrich_coefficients__coeff_2__m_3__r_30'
 'month__friedrich_coefficients__coeff_3__m_3__r_30'
 'month__max_langevin_fixed_point__m_3__r_30'
 'month__query_similarity_count__query_None__threshold_0.0'
 'day_of_month__query_similarity_count__query_None__threshold_0.0'
 'week_of_year__query_similarity_count__query_None__threshold_0.0'
 'day_of_year__query_similarity_count__query_None__threshold_0.0'] did not have any finite values. Filling with zeros.
  warnings.warn(

AssertionError: X and y must contain the same number of samples.